[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ['*']

solc_version = "0.8.19"

remappings = [
    "@solady/=lib/solady/src/",
    "src/=src/"
]

fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./script/config" },
]
coverage_exclude = ["test/**/*.sol", "script/**/*.sol", "lib/**/*.sol"]


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
base = "${BASE_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"



[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
polygon = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ETHERSCAN_API_KEY}" }
optimism = { key = "${ETHERSCAN_API_KEY}" }
