[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ['*']
# evm_version = "cancun"
solc_version = "0.8.19"
# viaIR = true
# optimizer = true
# optimizer_runs = 200
coverage_exclude = [
    "test/**/*",
    "script/**/*",
    "**/Mock*.sol",
    "lib/**/*"
]
coverage = [
    "src/SharePriceOracle/SharePriceOracle.sol",
    "src/libs/MsgCodec.sol",
    "src/lzEndpoint/LzEndpoint.sol"
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
amoy = "https://polygon-amoy.g.alchemy.com/v2/j5pYXkgWVoiy7Ehn2wnerPxGegQCbAlG"
sepolia= "https://eth-sepolia.g.alchemy.com/v2/fsum8AGsbu1XW3ToTQ9i-pSJDr5gGTJX"
arbitrum = "https://rpc.ankr.com/arbitrum_sepolia"


[etherscan]
# mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
sepolia = { key = "EG3PV77S3FP3YHFUTYNRQ5HZ4N7TWCRI5S" }
# polygon = { key = "${POLYGON_SCAN_KEY}" }
amoy = { key = "VTU1RF4V3G9E9WS5IH3SRW5IE5ZKXDRU3W" }

arbitrum = { key = "KTH1MJFIR15PM3QGXSB3D4JPMNDR1S37TM" }
