[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ['*']

solc_version = "0.8.19"

fs_permissions = [
    { access = "read-write", path = "./deployments" },
    { access = "read", path = "./script/config" },
]
coverage_exclude = ["test/**/*", "script/**/*", "**/Mock*.sol", "lib/**/*"]
coverage = [
    "src/SharePriceOracle/SharePriceOracle.sol",
    "src/libs/MsgCodec.sol",
    "src/lzEndpoint/LzEndpoint.sol",
]

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
polygon = "${RPC_POLYGON}"
base = "${RPC_BASE}"
arbitrum = "${RPC_ARBITRUM}"
optimism = "${RPC_OPTIMISM}"



[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
polygon = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ETHERSCAN_API_KEY}" }
optimism = { key = "${ETHERSCAN_API_KEY}" }
